### ISSUE TITLE
 call derivativesApi.getManifest throw Exception

### ISSUE THREAD

**Issue by wangsidong** [Autodesk-Forge/forge-api-java-client#28]
when i call the api derivativesApi.getManifest to verifyJobComplete it throw a Excetpion，
com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type com.autodesk.client.model.ManifestChildren$RoleEnum from String "Autodesk.AEC.ModelData": value not one of declared Enum instance names: [3d, 2d, graphics, thumbnail, manifest, Autodesk.CloudPlatform.PropertyDatabase]↵ at [Source: java.util.zip.GZIPInputStream@6d7191c1; line: 1, column: 1105] (through reference chain: com.autodesk.client.model.Manifest["derivatives"]->java.util.ArrayList[0]->com.autodesk.client.model.ManifestDerivative["children"]->java.util.ArrayList[1]->com.autodesk.client.model.ManifestChildren["role"])"
only rvt model has this error ,    ifc,dwfx,dwt can run.

**Comment by vaibhav-bhandari** [comment]
Is this issue fixed?
I am doing the similar thing (verifying the jobCompletion) but getting this error.
I doubt latest Maven library doesn't contain this fix yet.

**Comment by dukedhx** [comment]
the fix is on github only and not yet published - clone from github to get the fix

**Comment by vaibhav-bhandari** [comment]
Oh Ok.. Thanks

**Comment by wangsidong** [comment]
rvt model is solved

today when i use nwd model do this,it throw the same Excetpion out
com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type com.autodesk.client.model.ManifestChildren$TypeEnum from String "folder": value not one of declared Enum instance names: [geometry, view, resource, manifest]↵ at [Source: java.util.zip.GZIPInputStream@abb4f0a; line: 1, column: 1991] (through reference chain: com.autodesk.client.model.Manifest["derivatives"]->java.util.ArrayList[0]->com.autodesk.client.model.ManifestDerivative["children"]->java.util.ArrayList[0]->com.autodesk.client.model.ManifestChildren["children"]->java.util.ArrayList[1]->com.autodesk.client.model.ManifestChildren["type"])

**Comment by dukedhx** [comment]
@wangsidong will address this in the next commit

**Comment by THISISSUBBU** [comment]
I'm still getting the issue, But fix is there in the github but when using the maven fix is not there is maven source.

Is there any idea?

**Comment by dukedhx** [comment]
This is because the latest changes have yet to be published to maven so download from this repo to use the latest version

**Comment by THISISSUBBU** [comment]
Is there any idea when it will be published?, really we need to from maven repository. That is very helpful for us to deliver a feature.

We are waiting for it. Please do the needful as soon as possible

**Comment by ilseva** [comment]
> This is because the latest changes have yet to be published to maven so download from this repo to use the latest version
hi,
when will this fix will be published on maven? It need just a `mvn deploy`. Isn't it?
thanks.
